version: "3"
services:
  jq_postgres_local:
    image: jq_postgres_local
    container_name: jq_postgres_local
    build:
      context: ../
      dockerfile: devops/db.Dockerfile
    restart: always
    env_file:
      - common.env
    ports:
      - "5100:5432"
    volumes:
      - jq_pgdata_local:/var/lib/postgresql/data
    networks:
      master_network:
        aliases:
          - jq_postgres_local
  jq_backend_local:
    image: jq_backend_local
    container_name: jq_backend_local
    build:
      context: ../
      dockerfile: devops/Dockerfile
    depends_on:
      - jq_postgres_local
    restart: always
    env_file:
      - common.env
      - local.env
    environment:
      - APP_CONFIG=development
      - POSTGRES_HOST=jq_postgres_local
    volumes:
      - ../:/home/app
    ports:
      - 5000:5000
    networks:
      master_network:
        aliases:
          - jq_backend_local
networks:
  master_network:
    external: true
volumes:
  jq_pgdata_local:
