version: '3'

services:
  rublevka_frontend_prod:
    image: rublevka_frontend_prod
    container_name: rublevka_frontend_prod
    restart: always
    build:
      context: .
      args:
        - APP
        - APP_ENV
        - REACT_APP_ROISTAT_ID
        - REACT_APP_FACEBOOK_PIXEL_ID
        - REACT_APP_TARGETIX_PIXEL_ID
        - REACT_APP_GOOGLE_ANALYTICS_ID
        - REACT_APP_YANDEX_METRIKA_ID
        - REACT_APP_SENTRY_DSN
        - BUILD_ID
        - HOST
    ports:
      - '127.0.0.1:7070:8080'
    networks:
      master_network:
        aliases:
          - rublevka_frontend_prod

networks:
  master_network:
    external: true
