version: '3'

services:
  qj_staff_frontend_dev:
    environment:
      - REACT_APP_ENV=development
      - PUBLIC_URL=https://jq-staff-dev.sputnikproduction.com
    build:
      context: ./
    env_file:
      - common.env
    networks:
      master_network:
        aliases:
          - qj_staff_frontend_dev
networks:
  master_network:
    external: true
